---
version: "2"

plugins:
  rubocop:
    enabled: true
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
  reek:
    enabled: true
  git-legal:
    enabled: true

    config:
      languages:
      - ruby
